package com.tripmate.audit;

public enum AuditAction {
    USER_REGISTERED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,

    TRIP_CREATED,
    TRIP_UPDATED,
    TRIP_DELETED,

    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,

    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,

    ITINERARY_UPDATED,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    BOOKING_CREATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED
}
