@echo off
echo Checking for existing process on port 8080...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :8080 ^| findstr LISTENING') do (
    echo Killing PID %%a on port 8080...
    taskkill /PID %%a /F >nul 2>&1
)
echo Starting TripMate Backend...
cd /d "%~dp0backend"
mvn spring-boot:run
