ALTER TABLE bookings ADD COLUMN IF NOT EXISTS passenger_details TEXT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_point VARCHAR(255) NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS drop_point VARCHAR(255) NULL;
