ALTER TABLE bookings
    ADD COLUMN booking_source VARCHAR(30) NOT NULL DEFAULT 'EXTERNAL_MANUAL',
    ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'NOT_REQUIRED',
    ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'INR',
    ADD COLUMN provider_offer_id VARCHAR(120) NULL,
    ADD COLUMN traveler_name VARCHAR(120) NULL,
    ADD COLUMN traveler_email VARCHAR(180) NULL,
    ADD COLUMN traveler_mobile VARCHAR(20) NULL;
