CREATE TABLE discovery_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(220) NOT NULL UNIQUE,
    name VARCHAR(220) NOT NULL,
    slug VARCHAR(240) NOT NULL,
    item_type VARCHAR(30) NOT NULL,
    category VARCHAR(40) NOT NULL,
    subcategory VARCHAR(100),
    city VARCHAR(120),
    district VARCHAR(120),
    state VARCHAR(120),
    full_address VARCHAR(600),
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    short_description TEXT,
    detailed_description LONGTEXT,
    opening_hours VARCHAR(500),
    suggested_visit_minutes INT,
    best_time_to_visit VARCHAR(300),
    activity_duration INT,
    minimum_age INT,
    maximum_age INT,
    minimum_weight DECIMAL(7, 2),
    maximum_weight DECIMAL(7, 2),
    difficulty_level VARCHAR(30),
    safety_information TEXT,
    inclusions TEXT,
    exclusions TEXT,
    things_to_carry TEXT,
    accessibility_information TEXT,
    contact_phone VARCHAR(40),
    official_website VARCHAR(700),
    booking_url VARCHAR(700),
    cancellation_information TEXT,
    price_status VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    price_type VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    base_price DECIMAL(12, 2),
    source_name VARCHAR(180) NOT NULL,
    source_url VARCHAR(700) NOT NULL,
    source_last_checked_at DATETIME,
    verification_expires_at DATETIME,
    confidence_score DECIMAL(4, 3) NOT NULL DEFAULT 0.500,
    rating DECIMAL(3, 2),
    rating_count INT,
    popularity_score INT NOT NULL DEFAULT 0,
    family_friendly TINYINT(1),
    conflict_status VARCHAR(40),
    conflict_notes TEXT,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT,
    updated_by BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_discovery_items_location (latitude, longitude),
    INDEX idx_discovery_items_filters (enabled, item_type, category, price_status),
    INDEX idx_discovery_items_city (city, district, state),
    CONSTRAINT fk_discovery_items_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_discovery_items_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discovery_price_options (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    discovery_item_id BIGINT NOT NULL,
    label VARCHAR(120) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    maximum_amount DECIMAL(12, 2),
    price_type VARCHAR(30) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    price_status VARCHAR(30) NOT NULL,
    source_url VARCHAR(700) NOT NULL,
    last_verified_at DATETIME,
    expires_at DATETIME,
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_discovery_prices_item FOREIGN KEY (discovery_item_id) REFERENCES discovery_items (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discovery_images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    discovery_item_id BIGINT NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    source_page VARCHAR(1000) NOT NULL,
    source_name VARCHAR(180) NOT NULL,
    author_name VARCHAR(180),
    license_name VARCHAR(180),
    attribution VARCHAR(700),
    exact_image TINYINT(1) NOT NULL DEFAULT 1,
    primary_image TINYINT(1) NOT NULL DEFAULT 0,
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_discovery_images_item FOREIGN KEY (discovery_item_id) REFERENCES discovery_items (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
