spring:
  application:
    name: tripmate-backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tripmate?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

brevo:
  api-url: ${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
  api-key: ${TRIPMATE_BREVO_API_KEY:}
  sender-email: ${TRIPMATE_BREVO_SENDER_EMAIL:}
  sender-name: ${TRIPMATE_BREVO_SENDER_NAME:TripMate}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:dGhpcmlzYWRldjUzY3JldGtleWZvcnRyaXBtYXRlYXBwbG9jYWw=}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
